# Edgify Agent Version: 1.22.2

version: '3.8'
services:
  edgify-agent:
    restart: always
    container_name: edgify-agent
    image: 'edgify/edgify-agent:1.22.2'
    env_file:
      - edgify-agent-backend.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /edgify_agent/shared:/edgify_agent/shared
      - ~/.docker/config.json:/root/.docker/config.json
      - /edgify_agent/logs:/edgify_agent/logs
    network_mode: host
